name: Build and deploy WAR app to Azure Web App - TempPrediction

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn -f ./p02-TempPrediction-Cloud/pom.xml clean package

      # 4. List target directory to verify .war generation
      - name: List target directory
        run: dir ./p02-TempPrediction-Cloud/target

      # 5. Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: './p02-TempPrediction-Cloud/target/*.war'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # 1. Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # 2. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_33C99D2E169247608BC7EFECAF9DFAB1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35E5539E91A84CD29944B23B1ADF0746 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00D59F71C31E441695D9A270E2C947F0 }}
        
      # 3. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TempPrediction'
          slot-name: 'Production'
          package: './p02-TempPrediction-Cloud/target/*.war'
